## Main Purpose of both these functions is to create an inverse of a matrix, and cache its
## calculation, so all future attempts to find inverse of the same matrix
## will be picked up from cache and not recalculated (avoid expensive calculation)

## //====================================//
## FIRST FUNCTION, makeCacheMatrix
## //====================================//
## Creates a list of 'builder functions' related to the context of a matrix input, and has
## the ability to store matrix input (as well as the 'cache' for its inverse matrix, 
## calculated by second function

makeCacheMatrix <- function(x = matrix()) {
## Sets local assignment of matrix m to null
        m <- NULL
## Function below allows you to change previous matrix input
## in the list that contains previous outputs from 
## makeCacheMatrix. That is why we have << operator
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
## Below anonymous function call will return the matrix input that is fed to the 
## makecachematrix function
        get <- function() {x}
## Below function stores any input given into 'cache', and does it at the outer function
## level with the superassignment operator. 
        setinverse <- function(solve) {m <<- solve}
## This function allows one to invoke an inverse of a matrix, if such an inverse
## has been previously calculated. If none has, it will be a null
        getinverse <- function() {m}
## Creates a list, with functions that can be referenced by setting a call to makecachematrix
## given a particular matrix input
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}

## //====================================//
## SECOND FUNCTION, cacheSolve
## //====================================//
## Return a matrix that is the inverse of 'x'. If it doesn't exist in the 'cache', it will
## create it if it exists from cache, it will pull it from cacheinstead of calculating it
cacheSolve <- function(x, ...) 
## First function invokes a function from the list of functions built by makecachematrix
## which is the cached value of the current matrix input in list 'x'. Might/Might not exist. 
## Pushes matrix values to matrix 'm'
        m <- x$getinverse()
## Conditional statement checks matrix 'm' to see if it contains a previously-calculated
## matrix inverse. If it does (meaning matrix 'm' is not null), it returns the value
## as well as a message stating that the value was retrieved from cache
## If it doesn't exist, it will procede to calculate it in the next steps
        if(!is.null(m)) {
                          message("getting cached data for matrix inverse")
                          return(m)
                        }
## Everything below conditional statement takes place if matrix 'm' is null, meaning 
## no previous cache for the inverse matrix exists

## Function below invokes a function from list generated by makecachematrix to push the 
## matrix input given to makecachematrix into a matrix called 'data'
        data <- x$get()
## Function below carries out solve() function for matrix called 'data' and pushes 
## its value to a local matrix variable 'm'
        m <- solve(data, ...)
## Function below invokes a function from list generated by makecachematrix 
## to push the inverse matrix value calculated above to 'cache'
        x$setinverse(m)
## Returns calculated value of matrix inverse m
        m
}

